# -*- coding: utf-8 -*-
"""H-fix-5 analyze_gongliang 五阶段拆分哨兵。

锁两件事：
1. 结构（先红后绿）：拆分出的五个子函数必须存在于 gongliang 模块顶层
   （_prepare_inputs/_compute_position_sets/_apply_gong_point_rules/
   _apply_caps_and_direction/_build_gongliang_result）。
2. 行为（改动前后皆绿）：各子函数的阶段输出与拆分前实测一致——全部用
   源文第6章真实书例盘构造，钉值来自拆分前对 gongliang.py 源码行段的
   exec 捕获（/tmp/hfix5_gl_pins.json，等价性基线同批），不断言任何新规则。
"""
import pytest

from mangpai.objective import Pillars
from mangpai.subjective.gongliang import (
    _apply_caps_and_direction,
    _apply_gong_point_rules,
    _build_gongliang_result,
    _compute_position_sets,
    _prepare_inputs,
    analyze_gongliang,
)

# ── 源文第6章书例盘（与 test_gongliang.py 同源）──
PANS = {
    'LIJIACHENG': (['戊', '己', '庚', '丁'], ['辰', '未', '午', '亥']),
    'QIANLONG': (['辛', '丁', '庚', '丙'], ['卯', '酉', '午', '子']),
    'KELINTUN': (['丙', '丙', '乙', '戊'], ['戌', '申', '丑', '寅']),
    'JIANGJIESHI': (['丁', '庚', '己', '庚'], ['亥', '戌', '巳', '午']),
    'YUEFEI': (['癸', '乙', '甲', '己'], ['未', '卯', '子', '巳']),
    'LIU6': (['乙', '丙', '甲', '甲'], ['未', '戌', '子', '戌']),
    'LIU7': (['丙', '戊', '戊', '甲'], ['申', '戌', '寅', '寅']),
    'LIU8': (['壬', '戊', '丙', '壬'], ['寅', '申', '申', '辰']),
    'LIU9': (['壬', '戊', '癸', '庚'], ['寅', '申', '巳', '申']),
    'AONAXIXI': (['乙', '己', '己', '庚'], ['巳', '丑', '未', '午']),
    'YANXISHAN': (['癸', '辛', '乙', '丁'], ['未', '酉', '酉', '丑']),
    'PUTONG2': (['壬', '己', '乙', '丁'], ['子', '酉', '丑', '丑']),
    'PUTONG4': (['壬', '甲', '庚', '辛'], ['子', '辰', '午', '巳']),
}

# ── 拆分前实测钉值（九盘 × 五阶段；ph1 投影 + wa_list 长度）──
PIN = {
    'LIJIACHENG': {
        'ph1': {'day_gan': '庚', 'day_wx': '金', 'fei': ['month_gan', 'year_gan'], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_zhi', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [{'action': '墓用', 'auxiliary': True, 'desc': '未(土)入辰墓（宾位入墓，不做主功）', 'from': '年支(辰)', 'from_pos': 'year_zhi', 'non_day_tomb': True, 'to': '月支(未)', 'to_pos': 'month_zhi', 'type': '墓用'}, {'action': '墓用', 'auxiliary': True, 'desc': '亥(水)入辰墓（宾位入墓，不做主功）', 'from': '年支(辰)', 'from_pos': 'year_zhi', 'non_day_tomb': True, 'to': '时支(亥)', 'to_pos': 'hour_zhi', 'type': '墓用'}], 'wtypes': ['制用', '化用', '合用'], '_wa_list_len': 11, 'zb': {'bao_zhi': None, 'chong_lian': None, 'confidence': '中', 'party_strength': {'土': 11.25, '木': 4.0, '水': 4.0, '火': 5.75, '金': 6.5}, 'points': 0.0, 'reasons': ['净制：捕神「火」成势（5.8），贼神「水」孤立（无原神）且实存，制之干净'], 'zeishen_bushen': {'bushen_strength': 5.75, 'bushen_wx': '火', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '净', 'momentum_waste': False, 'reason': '净制：捕神「火」成势（5.8），贼神「水」孤立（无原神）且实存，制之干净', 'yuanshen_yi_zhi': True, 'zeishen_has_yuanshen': False, 'zeishen_isolated': True, 'zeishen_strength': 4.0, 'zeishen_wx': '水'}}, 'zb_bao': None, 'zb_clian': None, 'zb_jing': '净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 4, 'destructive_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi'], 'fei_cats': ['印'], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['官杀'], 'month_gan': ['印'], 'year_gan': ['印']}, 'gong_cats': ['印', '官杀', '比劫', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_zhi'], 'non_aux': [{'action': '化用', 'desc': '官杀(丁火)生印(土)生日主(庚金)，杀印相生化用做功', 'from': '日干(庚)', 'from_pos': 'day_gan', 'primary': True, 'to': '时干(丁)', 'to_pos': 'hour_gan', 'type': '杀印相生'}, {'action': '合用', 'desc': '未午合（日支参与）', 'from': '月支(未)', 'from_pos': 'month_zhi', 'soil_shengke': {'未': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(午)', 'to_pos': 'day_zhi', 'type': '地支合'}, {'action': '合用', 'desc': '午亥暗合（日支参与），主隐秘做功、暗中获取', 'from': '日支(午)', 'from_pos': 'day_zhi', 'to': '时支(亥)', 'to_pos': 'hour_zhi', 'type': '暗合'}, {'action': '克', 'desc': '亥水克午火', 'from': '时支(亥)', 'from_pos': 'hour_zhi', 'severity': 'normal', 'to': '日支(午)', 'to_pos': 'day_zhi', 'type': '克'}, {'action': '克', 'desc': '丁火克庚金', 'from': '时干(丁)', 'from_pos': 'hour_gan', 'severity': 'normal', 'to': '日干(庚)', 'to_pos': 'day_gan', 'type': '克'}], 'strong_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_zhi'], 'zhi_targets': ['day_gan', 'day_zhi']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': False, '_zb_bao_counted': False, '_zb_boost': 0.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 4.5, 'reasons': ['原神用神同制：hour_zhi(亥)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '库源/连墓：制局目标「亥(水)」之墓库「辰」在局，源头得库（+1层）', '连墓加层：月令「未」入墓于源头之库「辰」，提纲入库加大库之功量（+1层）', '月令做功：月令未直接参与核心做功，提纲得时得令（+0.5层）'], 'yuanshen_hit': '财+食伤', 'yuanshen_pos': 'hour_zhi'},
        'ph4': {'_strength_gl': '身强', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '化用', '合用']}, 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 4, 'reasons': ['原神用神同制：hour_zhi(亥)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '库源/连墓：制局目标「亥(水)」之墓库「辰」在局，源头得库（+1层）', '连墓加层：月令「未」入墓于源头之库「辰」，提纲入库加大库之功量（+1层）', '月令做功：月令未直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/化用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': False, 'zhi_jing': '净'},
        'ph5_result': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '化用', '合用']}, 'gong_points': 4.5, 'gong_shen_cats': ['印', '官杀', '比劫', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：hour_zhi(亥)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '库源/连墓：制局目标「亥(水)」之墓库「辰」在局，源头得库（+1层）', '连墓加层：月令「未」入墓于源头之库「辰」，提纲入库加大库之功量（+1层）', '月令做功：月令未直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/化用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '贼神捕神上游信号（净制=净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 100, 'strength': '身强', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': False, 'diff': 0, 'gongliang_level': 4, 'work_level': 4}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    },
    'QIANLONG': {
        'ph1': {'day_gan': '庚', 'day_wx': '金', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [], 'wtypes': ['制用', '合用'], '_wa_list_len': 14, 'zb': {'bao_zhi': None, 'chong_lian': {'chain': ['hour', 'day', 'month', 'year'], 'detected': True, 'has_chong': True, 'length': 3, 'links': [['冲', '子', '午'], ['克', '午', '酉'], ['冲', '酉', '卯']], 'nodes': ['子', '午', '酉', '卯'], 'points': 1, 'reason': '层层相制（冲链）：子->午->酉->卯，链长3（含冲），逐级相制（+1层）'}, 'confidence': '中', 'party_strength': {'土': 4.0, '木': 3.0, '水': 5.0, '火': 7.0, '金': 6.5}, 'points': 1.0, 'reasons': ['层层相制（冲链）：子->午->酉->卯，链长3（含冲），逐级相制（+1层）', '净制：捕神「火」成势（7.0），贼神「金」孤立（无原神）且实存，制之干净'], 'zeishen_bushen': {'bushen_strength': 7.0, 'bushen_wx': '火', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '净', 'momentum_waste': False, 'reason': '净制：捕神「火」成势（7.0），贼神「金」孤立（无原神）且实存，制之干净', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': False, 'zeishen_isolated': True, 'zeishen_strength': 6.5, 'zeishen_wx': '金'}}, 'zb_bao': None, 'zb_clian': {'chain': ['hour', 'day', 'month', 'year'], 'detected': True, 'has_chong': True, 'length': 3, 'links': [['冲', '子', '午'], ['克', '午', '酉'], ['冲', '酉', '卯']], 'nodes': ['子', '午', '酉', '卯'], 'points': 1, 'reason': '层层相制（冲链）：子->午->酉->卯，链长3（含冲），逐级相制（+1层）'}, 'zb_jing': '净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 6, 'destructive_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['官杀'], 'month_gan': ['官杀'], 'year_gan': ['比劫']}, 'gong_cats': ['官杀', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'non_aux': [{'action': '合用', 'desc': '辛丙合（非日干合，合制做功）', 'from': '年干(辛)', 'from_pos': 'year_gan', 'to': '时干(丙)', 'to_pos': 'hour_gan', 'type': '天干合'}, {'action': '冲', 'desc': '午子冲', 'efficiency_discount': True, 'from': '日支(午)', 'from_pos': 'day_zhi', 'primary': True, 'severity': 'normal', 'to': '时支(子)', 'to_pos': 'hour_zhi', 'type': '冲'}, {'action': '克', 'desc': '午火克酉金', 'direction': '反向', 'from': '日支(午)', 'from_pos': 'day_zhi', 'severity': 'normal', 'to': '月支(酉)', 'to_pos': 'month_zhi', 'type': '克'}, {'action': '克', 'desc': '丁火克庚金', 'from': '月干(丁)', 'from_pos': 'month_gan', 'severity': 'normal', 'to': '日干(庚)', 'to_pos': 'day_gan', 'type': '克'}, {'action': '克', 'desc': '丙火克庚金', 'from': '时干(丙)', 'from_pos': 'hour_gan', 'severity': 'normal', 'to': '日干(庚)', 'to_pos': 'day_gan', 'type': '克'}, {'action': '破', 'desc': '卯午破', 'from': '年支(卯)', 'from_pos': 'year_zhi', 'severity': 'high', 'to': '日支(午)', 'to_pos': 'day_zhi', 'type': '破'}], 'strong_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan'], 'zhi_targets': ['day_gan', 'day_zhi', 'hour_zhi', 'month_zhi']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': False, '_zb_bao_counted': False, '_zb_boost': 1.0, '_zb_pyramid': True, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 4.5, 'reasons': ['原神用神同制：day_zhi(午)含用神「印」与原神「官杀」同制（+2层，两层功量）', '七杀当财：官杀透干(month_gan)与制局目标(day_zhi/午)同根，七杀当财（+1层）', '层层相制：乾隆式金字塔冲链（子->午->酉->卯，链长3、以冲为骨），zb 党势判净制佐证（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）'], 'yuanshen_hit': '印+官杀', 'yuanshen_pos': 'day_zhi'},
        'ph4': {'_strength_gl': '身弱', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(午)含用神「印」与原神「官杀」同制（+2层，两层功量）', '七杀当财：官杀透干(month_gan)与制局目标(day_zhi/午)同根，七杀当财（+1层）', '层层相制：乾隆式金字塔冲链（子->午->酉->卯，链长3、以冲为骨），zb 党势判净制佐证（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': True, 'zhi_jing': '净'},
        'ph5_result': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'gong_points': 4.5, 'gong_shen_cats': ['官杀', '比劫', '财', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(午)含用神「印」与原神「官杀」同制（+2层，两层功量）', '七杀当财：官杀透干(month_gan)与制局目标(day_zhi/午)同根，七杀当财（+1层）', '层层相制：乾隆式金字塔冲链（子->午->酉->卯，链长3、以冲为骨），zb 党势判净制佐证（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '双轨对账：双轨冲突：做功层次L1（效率视角）与功量L4（富贵量级）差3层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=净、冲链检出、已据净制增强制净判定；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 100, 'strength': '身弱', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': True, 'diff': 3, 'gongliang_level': 4, 'note': '双轨冲突：做功层次L1（效率视角）与功量L4（富贵量级）差3层，宜复核（降档/封顶/体系口径差异）', 'work_level': 1}, 'yuanshen_yongshen': '印+官杀', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    },
    'KELINTUN': {
        'ph1': {'day_gan': '乙', 'day_wx': '木', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [], 'wtypes': ['制用', '合用', '生用'], '_wa_list_len': 11, 'zb': {'bao_zhi': {'detected': True, 'party': 8.0, 'pattern': '三合两翼', 'points': 1, 'reason': '包制：年(戌)、时(寅)同载「火」成势（party=8.0，被克「金」7.0），围制month柱（金），三合两翼（+1层）', 'target_party': 7.0, 'target_pillar': 'month', 'target_wx': '金', 'wrap_pillars': ['year', 'hour'], 'wrap_wx': '火'}, 'chong_lian': {'chain': ['month', 'hour', 'year'], 'detected': True, 'has_chong': True, 'length': 2, 'links': [['冲', '申', '寅'], ['克', '寅', '戌']], 'nodes': ['申', '寅', '戌'], 'points': 1, 'reason': '层层相制（冲链）：申->寅->戌，链长2（含冲），逐级相制（+1层）'}, 'confidence': '中', 'party_strength': {'土': 10.0, '木': 4.75, '水': 3.25, '火': 8.0, '金': 7.0}, 'points': 2.0, 'reasons': ['包制：年(戌)、时(寅)同载「火」成势（party=8.0，被克「金」7.0），围制month柱（金），三合两翼（+1层）', '层层相制（冲链）：申->寅->戌，链长2（含冲），逐级相制（+1层）', '净制：捕神「火」成势（8.0），贼神「金」孤立（原神同制）且实存，制之干净'], 'zeishen_bushen': {'bushen_strength': 8.0, 'bushen_wx': '火', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '净', 'momentum_waste': False, 'reason': '净制：捕神「火」成势（8.0），贼神「金」孤立（原神同制）且实存，制之干净', 'yuanshen_yi_zhi': True, 'zeishen_has_yuanshen': True, 'zeishen_isolated': True, 'zeishen_strength': 7.0, 'zeishen_wx': '金'}}, 'zb_bao': {'detected': True, 'party': 8.0, 'pattern': '三合两翼', 'points': 1, 'reason': '包制：年(戌)、时(寅)同载「火」成势（party=8.0，被克「金」7.0），围制month柱（金），三合两翼（+1层）', 'target_party': 7.0, 'target_pillar': 'month', 'target_wx': '金', 'wrap_pillars': ['year', 'hour'], 'wrap_wx': '火'}, 'zb_clian': {'chain': ['month', 'hour', 'year'], 'detected': True, 'has_chong': True, 'length': 2, 'links': [['冲', '申', '寅'], ['克', '寅', '戌']], 'nodes': ['申', '寅', '戌'], 'points': 1, 'reason': '层层相制（冲链）：申->寅->戌，链长2（含冲），逐级相制（+1层）'}, 'zb_jing': '净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 4, 'destructive_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['财'], 'month_gan': ['食伤'], 'year_gan': ['食伤']}, 'gong_cats': ['官杀', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'year_zhi'], 'non_aux': [{'action': '生用', 'desc': '伤官丙泄秀，生财(时干戊、年支戌、日支丑)、制杀(月支申)', 'efficiency_discount': True, 'from': '日干(乙)', 'from_pos': 'day_gan', 'primary': True, 'subtype': '食伤生财', 'to': '月干(丙)', 'to_pos': 'month_gan', 'type': '食伤', 'wood_fear_metal': True, 'wood_fire_xiuxiu': '泄秀吉（活木见火开花）'}, {'action': '合用', 'desc': '丑寅暗合（日支参与），主隐秘做功、暗中获取', 'efficiency_discount': True, 'from': '日支(丑)', 'from_pos': 'day_zhi', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '时支(寅)', 'to_pos': 'hour_zhi', 'type': '暗合', 'wood_fear_metal': True}, {'action': '克', 'desc': '寅木克丑土', 'from': '时支(寅)', 'from_pos': 'hour_zhi', 'severity': 'normal', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '日支(丑)', 'to_pos': 'day_zhi', 'type': '克'}, {'action': '克', 'desc': '乙木克戊土', 'efficiency_discount': True, 'from': '日干(乙)', 'from_pos': 'day_gan', 'severity': 'normal', 'to': '时干(戊)', 'to_pos': 'hour_gan', 'type': '克', 'wood_fear_metal': True}, {'action': '刑', 'desc': '戌丑刑', 'efficiency_discount': True, 'from': '年支(戌)', 'from_pos': 'year_zhi', 'gan_entombed': True, 'severity': 'normal', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}, '戌': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(丑)', 'to_pos': 'day_zhi', 'type': '刑'}], 'strong_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi'], 'zhi_targets': ['day_zhi', 'hour_gan']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': False, '_zb_bao_counted': True, '_zb_boost': 2.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 5.0, 'reasons': ['原神用神同制：day_zhi(丑)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '库源/连墓：制局目标「丑(土)」之墓库「戌」在局，源头得库（+1层）', '包局/包制：zb 净制佐证下采信围制（+1层）', '层层相制：zb 净制佐证下采信冲链（+1层）'], 'yuanshen_hit': '官杀+财', 'yuanshen_pos': 'day_zhi'},
        'ph4': {'_strength_gl': '从弱', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'level': 4, 'penalty': None, 'pocai_reason': '比劫夺财抑制：包制（围制官杀）结构下比劫为围制之一员（合杀库/制官杀），非夺财破财（不封顶）', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(丑)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '库源/连墓：制局目标「丑(土)」之墓库「戌」在局，源头得库（+1层）', '包局/包制：zb 净制佐证下采信围制（+1层）', '层层相制：zb 净制佐证下采信冲链（+1层）', '制净：被制用神与其原神俱制、无残存，制之干净', '比劫夺财抑制：命局为包制（围制官杀）结构，比劫作围制之一员（合杀库/制官杀），段氏「制财得财」之夺财不适用，不封顶', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': True, 'zhi_jing': '净'},
        'ph5_result': {'boundary': 'L3/L4边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'gong_points': 5.0, 'gong_shen_cats': ['官杀', '比劫', '财', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '比劫夺财抑制：包制（围制官杀）结构下比劫为围制之一员（合杀库/制官杀），非夺财破财（不封顶）', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(丑)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '库源/连墓：制局目标「丑(土)」之墓库「戌」在局，源头得库（+1层）', '包局/包制：zb 净制佐证下采信围制（+1层）', '层层相制：zb 净制佐证下采信冲链（+1层）', '制净：被制用神与其原神俱制、无残存，制之干净', '比劫夺财抑制：命局为包制（围制官杀）结构，比劫作围制之一员（合杀库/制官杀），段氏「制财得财」之夺财不适用，不封顶', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=98 落 L3/L4边界（不强制二选一，宜结合制净/做功细辨）', '双轨对账：双轨冲突：做功层次L2（效率视角）与功量L4（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=净、包制检出、冲链检出、已据净制增强制净判定；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 98, 'strength': '从弱', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': True, 'diff': 2, 'gongliang_level': 4, 'note': '双轨冲突：做功层次L2（效率视角）与功量L4（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', 'work_level': 2}, 'yuanshen_yongshen': '官杀+财', 'zeishen_bao_zhi': True, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    },
    'JIANGJIESHI': {
        'ph1': {'day_gan': '己', 'day_wx': '土', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [{'action': '墓用', 'desc': '巳(火)入戌墓', 'efficiency_discount': True, 'from': '月支(戌)', 'from_pos': 'month_zhi', 'soil_shengke': {'戌': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(巳)', 'to_pos': 'day_zhi', 'type': '墓用'}, {'action': '墓用', 'auxiliary': True, 'desc': '午(火)入戌墓（宾位入墓，不做主功）', 'from': '月支(戌)', 'from_pos': 'month_zhi', 'non_day_tomb': True, 'to': '时支(午)', 'to_pos': 'hour_zhi', 'type': '墓用'}], 'wtypes': ['制用', '墓用', '生用'], '_wa_list_len': 12, 'zb': {'bao_zhi': None, 'chong_lian': {'chain': ['month', 'year', 'day'], 'detected': True, 'has_chong': True, 'length': 2, 'links': [['克', '戌', '亥'], ['冲', '亥', '巳']], 'nodes': ['戌', '亥', '巳'], 'points': 1, 'reason': '层层相制（冲链）：戌->亥->巳，链长2（含冲），逐级相制（+1层）'}, 'confidence': '中', 'party_strength': {'土': 9.5, '木': 2.0, '水': 4.5, '火': 7.5, '金': 8.0}, 'points': 1.0, 'reasons': ['层层相制（冲链）：戌->亥->巳，链长2（含冲），逐级相制（+1层）', '制不净：贼神「水」之原神「金」残存未被制，封顶三层'], 'zeishen_bushen': {'bushen_strength': 9.5, 'bushen_wx': '土', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '不净', 'momentum_waste': False, 'reason': '制不净：贼神「水」之原神「金」残存未被制，封顶三层', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': True, 'zeishen_isolated': False, 'zeishen_strength': 4.5, 'zeishen_wx': '水'}}, 'zb_bao': None, 'zb_clian': {'chain': ['month', 'year', 'day'], 'detected': True, 'has_chong': True, 'length': 2, 'links': [['克', '戌', '亥'], ['冲', '亥', '巳']], 'nodes': ['戌', '亥', '巳'], 'points': 1, 'reason': '层层相制（冲链）：戌->亥->巳，链长2（含冲），逐级相制（+1层）'}, 'zb_jing': '不净'},
        'ph2': {'active_tomb_works': [{'action': '墓用', 'desc': '巳(火)入戌墓', 'efficiency_discount': True, 'from': '月支(戌)', 'from_pos': 'month_zhi', 'soil_shengke': {'戌': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(巳)', 'to_pos': 'day_zhi', 'type': '墓用'}], 'control_action_count': 2, 'destructive_positions': ['day_zhi', 'year_zhi'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['食伤'], 'month_gan': ['食伤'], 'year_gan': ['印']}, 'gong_cats': ['印', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_zhi', 'month_zhi', 'year_zhi'], 'non_aux': [{'action': '生用', 'desc': '伤官庚泄秀，生财(年支亥)', 'from': '日干(己)', 'from_pos': 'day_gan', 'primary': True, 'subtype': '食伤生财', 'to': '月干(庚)', 'to_pos': 'month_gan', 'type': '食伤'}, {'action': '生用', 'desc': '伤官庚泄秀，生财(年支亥)', 'from': '日干(己)', 'from_pos': 'day_gan', 'subtype': '食伤生财', 'to': '时干(庚)', 'to_pos': 'hour_gan', 'type': '食伤'}, {'action': '冲', 'desc': '亥巳冲', 'efficiency_discount': True, 'from': '年支(亥)', 'from_pos': 'year_zhi', 'severity': 'normal', 'to': '日支(巳)', 'to_pos': 'day_zhi', 'type': '冲'}, {'action': '墓用', 'desc': '巳(火)入戌墓', 'efficiency_discount': True, 'from': '月支(戌)', 'from_pos': 'month_zhi', 'soil_shengke': {'戌': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(巳)', 'to_pos': 'day_zhi', 'type': '墓用'}], 'strong_positions': ['day_zhi', 'year_zhi'], 'zhi_targets': ['day_zhi']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': True, '_zb_bao_counted': False, '_zb_boost': 0.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 0, 'hua_chengju': False, 'points': 3.5, 'reasons': ['原神用神同制：year_zhi(亥)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '入墓为功：局中墓用做功1处（+1层）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）'], 'yuanshen_hit': '官杀+财', 'yuanshen_pos': 'year_zhi'},
        'ph4': {'_strength_gl': '身强', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 3, 'reasons': ['原神用神同制：year_zhi(亥)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '入墓为功：局中墓用做功1处（+1层）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': False, 'zhi_jing': '不净'},
        'ph5_result': {'boundary': 'L2/L3边界', 'chain_length': 0, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['原神用神同制：year_zhi(亥)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '入墓为功：局中墓用做功1处（+1层）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=72 落 L2/L3边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 72, 'strength': '身强', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yuanshen_yongshen': '官杀+财', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    },
    'YUEFEI': {
        'ph1': {'day_gan': '甲', 'day_wx': '木', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': True, 'san_he_formed': False, 'tomb_works': [{'action': '墓用', 'auxiliary': True, 'desc': '卯(木)入未墓（宾位入墓，不做主功）', 'from': '年支(未)', 'from_pos': 'year_zhi', 'non_day_tomb': True, 'to': '月支(卯)', 'to_pos': 'month_zhi', 'type': '墓用'}], 'wtypes': ['制用', '合用'], '_wa_list_len': 11, 'zb': {'bao_zhi': {'detected': True, 'party': 6.25, 'pattern': '透干成势', 'points': 1, 'reason': '包制：年(未)、时(巳)同载「土」成势（party=6.2，被克「水」4.2），围制day柱（水），透干成势（+1层）', 'target_party': 4.25, 'target_pillar': 'day', 'target_wx': '水', 'wrap_pillars': ['year', 'hour'], 'wrap_wx': '土'}, 'chong_lian': None, 'confidence': '中', 'party_strength': {'土': 6.25, '木': 9.0, '水': 4.25, '火': 6.0, '金': 3.0}, 'points': 1.0, 'reasons': ['包制：年(未)、时(巳)同载「土」成势（party=6.2，被克「水」4.2），围制day柱（水），透干成势（+1层）', '净制：捕神「土」成势（6.2），贼神「水」孤立（无原神）且实存，制之干净'], 'zeishen_bushen': {'bushen_strength': 6.25, 'bushen_wx': '土', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '净', 'momentum_waste': False, 'reason': '净制：捕神「土」成势（6.2），贼神「水」孤立（无原神）且实存，制之干净', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': False, 'zeishen_isolated': True, 'zeishen_strength': 4.25, 'zeishen_wx': '水'}}, 'zb_bao': {'detected': True, 'party': 6.25, 'pattern': '透干成势', 'points': 1, 'reason': '包制：年(未)、时(巳)同载「土」成势（party=6.2，被克「水」4.2），围制day柱（水），透干成势（+1层）', 'target_party': 4.25, 'target_pillar': 'day', 'target_wx': '水', 'wrap_pillars': ['year', 'hour'], 'wrap_wx': '土'}, 'zb_clian': None, 'zb_jing': '净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 4, 'destructive_positions': ['day_zhi', 'hour_zhi', 'year_zhi'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['财'], 'month_gan': ['比劫'], 'year_gan': ['印']}, 'gong_cats': ['印', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_zhi', 'year_zhi'], 'non_aux': [{'action': '合用', 'desc': '甲己合，合财', 'from': '日干(甲)', 'from_pos': 'day_gan', 'to': '时干(己)', 'to_pos': 'hour_gan', 'type': '天干合'}, {'action': '克', 'desc': '子水克巳火', 'from': '日支(子)', 'from_pos': 'day_zhi', 'primary': True, 'severity': 'normal', 'to': '时支(巳)', 'to_pos': 'hour_zhi', 'type': '克'}, {'action': '刑', 'desc': '卯子刑', 'from': '月支(卯)', 'from_pos': 'month_zhi', 'severity': 'normal', 'to': '日支(子)', 'to_pos': 'day_zhi', 'type': '刑'}, {'action': '穿', 'desc': '未子穿', 'efficiency_discount': True, 'from': '年支(未)', 'from_pos': 'year_zhi', 'severity': 'high', 'soil_shengke': {'未': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(子)', 'to_pos': 'day_zhi', 'type': '穿'}], 'strong_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'year_zhi'], 'zhi_targets': ['day_zhi', 'hour_zhi']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': False, '_zb_bao_counted': True, '_zb_boost': 1.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 3.5, 'reasons': ['原神用神同制：hour_zhi(巳)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '包局/包制：zb 净制佐证下采信围制（+1层）', '月令做功：月令卯直接参与核心做功，提纲得时得令（+0.5层）'], 'yuanshen_hit': '财+食伤', 'yuanshen_pos': 'hour_zhi'},
        'ph4': {'_strength_gl': '身强', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 3, 'reasons': ['原神用神同制：hour_zhi(巳)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '包局/包制：zb 净制佐证下采信围制（+1层）', '月令做功：月令卯直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '用神方向标注：忌神制用神（severe）——扶抑层凶向，与做功层口径并列标注，不降层功（方向封顶/否决由财命/官命/职业各自消费）', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [{'kind': '忌神制用神', 'reason': '忌神制用神·印夺食：身强食伤为用神、印为忌神，1处印制食伤（印2柱），段氏「用神制忌神则吉」之逆=忌神制用神凶（枭神夺食（食伤主财源/自由/子女））', 'severity': 'severe'}], 'zb_jing_adopted': True, 'zhi_jing': '净'},
        'ph5_result': {'boundary': 'L3/L4边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['原神用神同制：hour_zhi(巳)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '包局/包制：zb 净制佐证下采信围制（+1层）', '月令做功：月令卯直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '用神方向标注：忌神制用神（severe）——扶抑层凶向，与做功层口径并列标注，不降层功（方向封顶/否决由财命/官命/职业各自消费）', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=86 落 L3/L4边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=净、包制检出、已据净制增强制净判定；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 86, 'strength': '身强', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yongshen_xiong': [{'kind': '忌神制用神', 'reason': '忌神制用神·印夺食：身强食伤为用神、印为忌神，1处印制食伤（印2柱），段氏「用神制忌神则吉」之逆=忌神制用神凶（枭神夺食（食伤主财源/自由/子女））', 'severity': 'severe'}], 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': True, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    },
    'LIU8': {
        'ph1': {'day_gan': '丙', 'day_wx': '火', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [], 'wtypes': ['制用', '生用'], '_wa_list_len': 15, 'zb': {'bao_zhi': None, 'chong_lian': {'chain': ['month', 'year', 'hour'], 'detected': True, 'has_chong': True, 'length': 2, 'links': [['冲', '申', '寅'], ['克', '寅', '辰']], 'nodes': ['申', '寅', '辰'], 'points': 1, 'reason': '层层相制（冲链）：申->寅->辰，链长2（含冲），逐级相制（+1层）'}, 'confidence': '中', 'party_strength': {'土': 7.0, '木': 6.0, '水': 9.0, '火': 4.25, '金': 6.75}, 'points': 1.0, 'reasons': ['层层相制（冲链）：申->寅->辰，链长2（含冲），逐级相制（+1层）', '制不净：贼神「木」之原神「水」残存未被制，封顶三层'], 'zeishen_bushen': {'bushen_strength': 6.75, 'bushen_wx': '金', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '不净', 'momentum_waste': False, 'reason': '制不净：贼神「木」之原神「水」残存未被制，封顶三层', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': True, 'zeishen_isolated': False, 'zeishen_strength': 6.0, 'zeishen_wx': '木'}}, 'zb_bao': None, 'zb_clian': {'chain': ['month', 'year', 'hour'], 'detected': True, 'has_chong': True, 'length': 2, 'links': [['冲', '申', '寅'], ['克', '寅', '辰']], 'nodes': ['申', '寅', '辰'], 'points': 1, 'reason': '层层相制（冲链）：申->寅->辰，链长2（含冲），逐级相制（+1层）'}, 'zb_jing': '不净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 3, 'destructive_positions': ['day_gan', 'day_zhi', 'hour_gan', 'year_gan', 'year_zhi'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['官杀'], 'month_gan': ['食伤'], 'year_gan': ['官杀']}, 'gong_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_gan', 'year_gan', 'year_zhi'], 'non_aux': [{'action': '生用', 'desc': '食神戊泄秀，生财(月支申、日支申)、制杀(年干壬、时干壬)', 'from': '日干(丙)', 'from_pos': 'day_gan', 'primary': True, 'subtype': '食伤生财', 'to': '月干(戊)', 'to_pos': 'month_gan', 'type': '食伤'}, {'action': '冲', 'desc': '寅申冲', 'from': '年支(寅)', 'from_pos': 'year_zhi', 'severity': 'normal', 'to': '日支(申)', 'to_pos': 'day_zhi', 'type': '冲'}, {'action': '克', 'desc': '壬水克丙火', 'from': '年干(壬)', 'from_pos': 'year_gan', 'severity': 'normal', 'to': '日干(丙)', 'to_pos': 'day_gan', 'type': '克'}, {'action': '克', 'desc': '壬水克丙火', 'efficiency_discount': True, 'from': '时干(壬)', 'from_pos': 'hour_gan', 'gan_entombed': True, 'severity': 'normal', 'to': '日干(丙)', 'to_pos': 'day_gan', 'type': '克'}], 'strong_positions': ['day_gan', 'day_zhi', 'hour_gan', 'year_gan', 'year_zhi'], 'zhi_targets': ['day_gan', 'day_zhi']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': False, '_zb_bao_counted': False, '_zb_boost': 0.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 4.0, 'reasons': ['原神用神同制：day_zhi(申)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '七杀当财：官杀透干(year_gan)与制局目标(day_zhi/申)同根，七杀当财（+1层）', '包局2.6：年时天干包局/十神包局（官杀），包围月日且制化所包（+1层）'], 'yuanshen_hit': '财+食伤', 'yuanshen_pos': 'day_zhi'},
        'ph4': {'_strength_gl': '从弱', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用']}, 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(申)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '七杀当财：官杀透干(year_gan)与制局目标(day_zhi/申)同根，七杀当财（+1层）', '包局2.6：年时天干包局/十神包局（官杀），包围月日且制化所包（+1层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': False, 'zhi_jing': '不净'},
        'ph5_result': {'boundary': 'L2/L3边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用']}, 'gong_points': 4.0, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(申)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '七杀当财：官杀透干(year_gan)与制局目标(day_zhi/申)同根，七杀当财（+1层）', '包局2.6：年时天干包局/十神包局（官杀），包围月日且制化所包（+1层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=68 落 L2/L3边界（不强制二选一，宜结合制净/做功细辨）', '双轨对账：双轨冲突：做功层次L1（效率视角）与功量L3（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 68, 'strength': '从弱', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': True, 'diff': 2, 'gongliang_level': 3, 'note': '双轨冲突：做功层次L1（效率视角）与功量L3（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', 'work_level': 1}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    },
    'PUTONG2': {
        'ph1': {'day_gan': '乙', 'day_wx': '木', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [], 'wtypes': ['制用', '合用', '生用'], '_wa_list_len': 11, 'zb': {'bao_zhi': None, 'chong_lian': None, 'confidence': '中', 'party_strength': {'土': 7.0, '木': 4.5, '水': 7.0, '火': 3.0, '金': 7.0}, 'points': 0.0, 'reasons': ['制不净：贼神「水」之原神「金」残存未被制，封顶三层'], 'zeishen_bushen': {'bushen_strength': 7.0, 'bushen_wx': '土', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '不净', 'momentum_waste': False, 'reason': '制不净：贼神「水」之原神「金」残存未被制，封顶三层', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': True, 'zeishen_isolated': False, 'zeishen_strength': 7.0, 'zeishen_wx': '水'}}, 'zb_bao': None, 'zb_clian': None, 'zb_jing': '不净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 3, 'destructive_positions': ['day_gan', 'month_gan'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['食伤'], 'month_gan': ['财'], 'year_gan': ['印']}, 'gong_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财'], 'involved_positions': ['day_gan', 'day_zhi', 'month_gan', 'month_zhi', 'year_zhi'], 'non_aux': [{'action': '生用', 'desc': '食神丁泄秀，生财(月干己、日支丑、时支丑)、制杀(月支酉)', 'from': '日干(乙)', 'from_pos': 'day_gan', 'primary': True, 'subtype': '食伤生财', 'to': '时干(丁)', 'to_pos': 'hour_gan', 'type': '食伤', 'wood_fire_xiuxiu': '见火反焚（死木忌旺火）'}, {'action': '合用', 'desc': '子丑合（日支参与）', 'from': '年支(子)', 'from_pos': 'year_zhi', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '日支(丑)', 'to_pos': 'day_zhi', 'type': '地支合'}, {'action': '半成势', 'desc': '酉丑半合金局，气未全', 'from': '月支(酉)', 'from_pos': 'month_zhi', 'participants': ['month_zhi', 'day_zhi'], 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '日支(丑)', 'to_pos': 'day_zhi', 'type': '半合'}, {'action': '克', 'desc': '乙木克己土', 'direction': '正向', 'from': '日干(乙)', 'from_pos': 'day_gan', 'severity': 'normal', 'target_vulnerable': '轻', 'to': '月干(己)', 'to_pos': 'month_gan', 'type': '克'}], 'strong_positions': ['day_gan', 'day_zhi', 'month_gan', 'month_zhi', 'year_zhi'], 'zhi_targets': ['month_gan']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': False, '_zb_bao_counted': False, '_zb_boost': 0.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 2.5, 'reasons': ['带象：month柱己酉干生支，承「财」象且参与做功（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '墓库属性：墓库「丑」参与做功，库之属性加层（+1层）'], 'yuanshen_hit': None, 'yuanshen_pos': None},
        'ph4': {'_strength_gl': '身弱', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'level': 1, 'penalty': '相生之功', 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 2, 'reasons': ['带象：month柱己酉干生支，承「财」象且参与做功（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '墓库属性：墓库「丑」参与做功，库之属性加层（+1层）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制，封顶于三层（达不到四层）', '普通四柱特征：仅以相生做功，无制局，功量较小', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': False, 'zhi_jing': '不净'},
        'ph5_result': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财'], 'fugui_pinjian': '第一档·小富小贵（普通偏上）', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'gong_points': 2.5, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 1, 'penalty': '相生之功', 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '科级-处级', 'raw_level': 2, 'reasons': ['带象：month柱己酉干生支，承「财」象且参与做功（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '墓库属性：墓库「丑」参与做功，库之属性加层（+1层）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制，封顶于三层（达不到四层）', '普通四柱特征：仅以相生做功，无制局，功量较小', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '双轨对账：双轨冲突：做功层次L3（效率视角）与功量L1（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=不净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 0, 'strength': '身弱', 'tier_name': '小富小贵', 'wealth_grade': '百万级', 'work_level_duizhang': {'conflict': True, 'diff': -2, 'gongliang_level': 1, 'note': '双轨冲突：做功层次L3（效率视角）与功量L1（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', 'work_level': 3}, 'yuanshen_yongshen': None, 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    },
    'AONAXIXI': {
        'ph1': {'day_gan': '己', 'day_wx': '土', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [], 'wtypes': ['制用', '合用', '生用'], '_wa_list_len': 10, 'zb': {'bao_zhi': None, 'chong_lian': None, 'confidence': '中', 'party_strength': {'土': 12.25, '木': 3.25, '水': 2.25, '火': 6.0, '金': 8.5}, 'points': 0.0, 'reasons': ['制不净：贼神「木」之原神「水」残存未被制，封顶三层'], 'zeishen_bushen': {'bushen_strength': 8.5, 'bushen_wx': '金', 'cheng_dang': True, 'confidence': '中', 'jing_zhi': '不净', 'momentum_waste': False, 'reason': '制不净：贼神「木」之原神「水」残存未被制，封顶三层', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': False, 'zeishen_isolated': True, 'zeishen_strength': 3.25, 'zeishen_wx': '木'}}, 'zb_bao': None, 'zb_clian': None, 'zb_jing': '不净'},
        'ph2': {'active_tomb_works': [], 'control_action_count': 4, 'destructive_positions': ['day_gan', 'day_zhi', 'month_zhi', 'year_gan'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['食伤'], 'month_gan': ['比劫'], 'year_gan': ['官杀']}, 'gong_cats': ['印', '官杀', '比劫', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_zhi', 'year_gan'], 'non_aux': [{'action': '合用', 'desc': '乙庚合（非日干合，合制做功）', 'from': '年干(乙)', 'from_pos': 'year_gan', 'to': '时干(庚)', 'to_pos': 'hour_gan', 'type': '天干合'}, {'action': '生用', 'desc': '伤官庚泄秀，制杀(年干乙)', 'from': '日干(己)', 'from_pos': 'day_gan', 'subtype': '食伤制杀', 'to': '时干(庚)', 'to_pos': 'hour_gan', 'type': '食伤'}, {'action': '合用', 'desc': '未午合（日支参与）', 'from': '日支(未)', 'from_pos': 'day_zhi', 'primary': True, 'soil_shengke': {'未': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '时支(午)', 'to_pos': 'hour_zhi', 'type': '地支合'}, {'action': '冲', 'desc': '丑未冲', 'from': '月支(丑)', 'from_pos': 'month_zhi', 'severity': 'normal', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}, '未': {'cui_jin': True, 'hui_huo': False, 'ke_shui': '强', 'sheng_jin': False, 'wet': False}}, 'to': '日支(未)', 'to_pos': 'day_zhi', 'type': '冲'}, {'action': '克', 'desc': '乙木克己土', 'from': '年干(乙)', 'from_pos': 'year_gan', 'severity': 'normal', 'to': '日干(己)', 'to_pos': 'day_gan', 'type': '克'}], 'strong_positions': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_zhi', 'year_gan'], 'zhi_targets': ['day_gan', 'day_zhi']},
        'ph3': {'_fang_ju_formed': True, '_rumu_counted': False, '_zb_bao_counted': False, '_zb_boost': 0.0, '_zb_pyramid': False, '_zhiku_counted': True, '_zhiku_tombs': ['未'], 'chain_len': 1, 'hua_chengju': False, 'points': 6.5, 'reasons': ['原神用神同制：month_zhi(丑)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '制墓库：制局冲/刑制墓库「未」（+2层）', '包局/包制：方局（三会）成势围制（+1层）', '月令做功：月令丑直接参与核心做功，提纲得时得令（+0.5层）', '开库加层：做功墓库「未」逢刑冲开库，功上加功（+1层）'], 'yuanshen_hit': '财+食伤', 'yuanshen_pos': 'month_zhi'},
        'ph4': {'_strength_gl': '从强', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 4, 'reasons': ['原神用神同制：month_zhi(丑)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '制墓库：制局冲/刑制墓库「未」（+2层）', '包局/包制：方局（三会）成势围制（+1层）', '月令做功：月令丑直接参与核心做功，提纲得时得令（+0.5层）', '开库加层：做功墓库「未」逢刑冲开库，功上加功（+1层）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制（方局围制+制库双结构，书判四层功量（理象学6470-6474），不净封顶不适用）', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': False, 'zhi_jing': '不净'},
        'ph5_result': {'boundary': 'L3/L4边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'gong_points': 6.5, 'gong_shen_cats': ['印', '官杀', '比劫', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：month_zhi(丑)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '制墓库：制局冲/刑制墓库「未」（+2层）', '包局/包制：方局（三会）成势围制（+1层）', '月令做功：月令丑直接参与核心做功，提纲得时得令（+0.5层）', '开库加层：做功墓库「未」逢刑冲开库，功上加功（+1层）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制（方局围制+制库双结构，书判四层功量（理象学6470-6474），不净封顶不适用）', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=94 落 L3/L4边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 94, 'strength': '从强', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 4, 'work_level': 3}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    },
    'YANXISHAN': {
        'ph1': {'day_gan': '乙', 'day_wx': '木', 'fei': [], 'gshen': ['day_gan', 'day_zhi', 'hour_gan', 'hour_zhi', 'month_gan', 'month_zhi', 'year_gan', 'year_zhi'], 'has_severe_harm': False, 'san_he_formed': False, 'tomb_works': [{'action': '墓用', 'auxiliary': True, 'desc': '酉(金)入丑墓（宾位入墓，不做主功）', 'from': '时支(丑)', 'from_pos': 'hour_zhi', 'non_day_tomb': True, 'to': '月支(酉)', 'to_pos': 'month_zhi', 'type': '墓用'}, {'action': '墓用', 'desc': '酉(金)入丑墓', 'from': '时支(丑)', 'from_pos': 'hour_zhi', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '日支(酉)', 'to_pos': 'day_zhi', 'type': '墓用'}], 'wtypes': ['制用', '墓用', '生用'], '_wa_list_len': 13, 'zb': {'bao_zhi': None, 'chong_lian': None, 'confidence': '中', 'party_strength': {'土': 5.25, '木': 4.25, '水': 6.0, '火': 4.0, '金': 9.0}, 'points': 0.0, 'reasons': [], 'zeishen_bushen': {'bushen_strength': 0.0, 'bushen_wx': '', 'cheng_dang': False, 'confidence': '中', 'jing_zhi': '无制', 'momentum_waste': False, 'reason': '命局无制局做功，不论净制', 'yuanshen_yi_zhi': False, 'zeishen_has_yuanshen': False, 'zeishen_isolated': False, 'zeishen_strength': 0.0, 'zeishen_wx': ''}}, 'zb_bao': None, 'zb_clian': None, 'zb_jing': '无制'},
        'ph2': {'active_tomb_works': [{'action': '墓用', 'desc': '酉(金)入丑墓', 'from': '时支(丑)', 'from_pos': 'hour_zhi', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '日支(酉)', 'to_pos': 'day_zhi', 'type': '墓用'}], 'control_action_count': 3, 'destructive_positions': ['day_gan', 'month_gan'], 'fei_cats': [], 'gan_cats': {'day_gan': ['比劫'], 'hour_gan': ['食伤'], 'month_gan': ['官杀'], 'year_gan': ['印']}, 'gong_cats': ['印', '官杀', '比劫', '财', '食伤'], 'involved_cats': ['印', '官杀', '比劫', '财'], 'involved_positions': ['day_gan', 'day_zhi', 'hour_zhi', 'month_gan', 'month_zhi'], 'non_aux': [{'action': '生用', 'desc': '食神丁泄秀，生财(年支未、时支丑)、制杀(月干辛、月支酉、日支酉)', 'from': '日干(乙)', 'from_pos': 'day_gan', 'primary': True, 'subtype': '食伤生财', 'to': '时干(丁)', 'to_pos': 'hour_gan', 'type': '食伤', 'wood_fire_xiuxiu': '见火反焚（死木忌旺火）'}, {'action': '克', 'desc': '辛金克乙木', 'from': '月干(辛)', 'from_pos': 'month_gan', 'severity': 'normal', 'to': '日干(乙)', 'to_pos': 'day_gan', 'type': '克'}, {'action': '刑', 'desc': '酉酉刑（自刑）', 'from': '月支(酉)', 'from_pos': 'month_zhi', 'severity': 'normal', 'to': '日支(酉)', 'to_pos': 'day_zhi', 'type': '刑'}, {'action': '墓用', 'desc': '酉(金)入丑墓', 'from': '时支(丑)', 'from_pos': 'hour_zhi', 'soil_shengke': {'丑': {'cui_jin': False, 'hui_huo': True, 'ke_shui': '弱', 'sheng_jin': True, 'wet': True}}, 'to': '日支(酉)', 'to_pos': 'day_zhi', 'type': '墓用'}], 'strong_positions': ['day_gan', 'month_gan'], 'zhi_targets': ['day_gan', 'day_zhi']},
        'ph3': {'_fang_ju_formed': False, '_rumu_counted': True, '_zb_bao_counted': False, '_zb_boost': 0.0, '_zb_pyramid': False, '_zhiku_counted': False, '_zhiku_tombs': [], 'chain_len': 1, 'hua_chengju': False, 'points': 3.5, 'reasons': ['入墓为功：局中墓用做功1处（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '化用成局/从杀格：杀印相生化用、官杀「金」党势成(6字)、日主从弱(比劫1字)，纯化用路径（+2层，化用成局为高层功量）'], 'yuanshen_hit': None, 'yuanshen_pos': None},
        'ph4': {'_strength_gl': '从弱', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'raw_level': 3, 'reasons': ['入墓为功：局中墓用做功1处（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '化用成局/从杀格：杀印相生化用、官杀「金」党势成(6字)、日主从弱(比劫1字)，纯化用路径（+2层，化用成局为高层功量）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'yongshen_xiong': [], 'zb_jing_adopted': False, 'zhi_jing': '不净'},
        'ph5_result': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['入墓为功：局中墓用做功1处（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '化用成局/从杀格：杀印相生化用、官杀「金」党势成(6字)、日主从弱(比劫1字)，纯化用路径（+2层，化用成局为高层功量）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'score': 76, 'strength': '从弱', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yuanshen_yongshen': None, 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '无制', 'zhi_jing': '不净'},
    },
}

# ── Pillars 对象签名端到端钉值（拆分前实测，dataclass 位置参数构造）──
PILLARS_PIN = {
    'JIANGJIESHI': {'boundary': 'L2/L3边界', 'chain_length': 0, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['原神用神同制：year_zhi(亥)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '入墓为功：局中墓用做功1处（+1层）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=72 落 L2/L3边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 72, 'strength': '身强', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yuanshen_yongshen': '官杀+财', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'LIJIACHENG': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '化用', '合用']}, 'gong_points': 4.5, 'gong_shen_cats': ['印', '官杀', '比劫', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：hour_zhi(亥)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '库源/连墓：制局目标「亥(水)」之墓库「辰」在局，源头得库（+1层）', '连墓加层：月令「未」入墓于源头之库「辰」，提纲入库加大库之功量（+1层）', '月令做功：月令未直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/化用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '贼神捕神上游信号（净制=净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 100, 'strength': '身强', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': False, 'diff': 0, 'gongliang_level': 4, 'work_level': 4}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
}

# ── 拆分前 analyze_gongliang 全量输出（十三盘，端到端）──
BOOK_A = {
    'LIJIACHENG': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '化用', '合用']}, 'gong_points': 4.5, 'gong_shen_cats': ['印', '官杀', '比劫', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：hour_zhi(亥)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '库源/连墓：制局目标「亥(水)」之墓库「辰」在局，源头得库（+1层）', '连墓加层：月令「未」入墓于源头之库「辰」，提纲入库加大库之功量（+1层）', '月令做功：月令未直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/化用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '贼神捕神上游信号（净制=净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 100, 'strength': '身强', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': False, 'diff': 0, 'gongliang_level': 4, 'work_level': 4}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    'QIANLONG': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'gong_points': 4.5, 'gong_shen_cats': ['官杀', '比劫', '财', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(午)含用神「印」与原神「官杀」同制（+2层，两层功量）', '七杀当财：官杀透干(month_gan)与制局目标(day_zhi/午)同根，七杀当财（+1层）', '层层相制：乾隆式金字塔冲链（子->午->酉->卯，链长3、以冲为骨），zb 党势判净制佐证（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '双轨对账：双轨冲突：做功层次L1（效率视角）与功量L4（富贵量级）差3层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=净、冲链检出、已据净制增强制净判定；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 100, 'strength': '身弱', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': True, 'diff': 3, 'gongliang_level': 4, 'note': '双轨冲突：做功层次L1（效率视角）与功量L4（富贵量级）差3层，宜复核（降档/封顶/体系口径差异）', 'work_level': 1}, 'yuanshen_yongshen': '印+官杀', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    'KELINTUN': {'boundary': 'L3/L4边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'gong_points': 5.0, 'gong_shen_cats': ['官杀', '比劫', '财', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '比劫夺财抑制：包制（围制官杀）结构下比劫为围制之一员（合杀库/制官杀），非夺财破财（不封顶）', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(丑)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '库源/连墓：制局目标「丑(土)」之墓库「戌」在局，源头得库（+1层）', '包局/包制：zb 净制佐证下采信围制（+1层）', '层层相制：zb 净制佐证下采信冲链（+1层）', '制净：被制用神与其原神俱制、无残存，制之干净', '比劫夺财抑制：命局为包制（围制官杀）结构，比劫作围制之一员（合杀库/制官杀），段氏「制财得财」之夺财不适用，不封顶', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=98 落 L3/L4边界（不强制二选一，宜结合制净/做功细辨）', '双轨对账：双轨冲突：做功层次L2（效率视角）与功量L4（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=净、包制检出、冲链检出、已据净制增强制净判定；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 98, 'strength': '从弱', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': True, 'diff': 2, 'gongliang_level': 4, 'note': '双轨冲突：做功层次L2（效率视角）与功量L4（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', 'work_level': 2}, 'yuanshen_yongshen': '官杀+财', 'zeishen_bao_zhi': True, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    'JIANGJIESHI': {'boundary': 'L2/L3边界', 'chain_length': 0, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['原神用神同制：year_zhi(亥)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '入墓为功：局中墓用做功1处（+1层）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=72 落 L2/L3边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 72, 'strength': '身强', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yuanshen_yongshen': '官杀+财', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'YUEFEI': {'boundary': 'L3/L4边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['原神用神同制：hour_zhi(巳)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '包局/包制：zb 净制佐证下采信围制（+1层）', '月令做功：月令卯直接参与核心做功，提纲得时得令（+0.5层）', '制净：被制用神与其原神俱制、无残存，制之干净', '用神方向标注：忌神制用神（severe）——扶抑层凶向，与做功层口径并列标注，不降层功（方向封顶/否决由财命/官命/职业各自消费）', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=86 落 L3/L4边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=净、包制检出、已据净制增强制净判定；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 86, 'strength': '身强', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yongshen_xiong': [{'kind': '忌神制用神', 'reason': '忌神制用神·印夺食：身强食伤为用神、印为忌神，1处印制食伤（印2柱），段氏「用神制忌神则吉」之逆=忌神制用神凶（枭神夺食（食伤主财源/自由/子女））', 'severity': 'severe'}], 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': True, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '净', 'zhi_jing': '净'},
    'LIU6': {'boundary': 'L1/L2边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第二档·中富中贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用']}, 'gong_points': 2.5, 'gong_shen_cats': ['印', '比劫', '财', '食伤'], 'level': 2, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '处级-厅级', 'raw_level': 2, 'reasons': ['原神用神同制：hour_zhi(戌)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）', '制不净：日柱被穿，做功质量受损，封顶于三层（达不到四层）', '复合结构：制用/生用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=44 落 L1/L2边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不成、包制检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 44, 'strength': '中和', 'tier_name': '中富中贵', 'wealth_grade': '千万-亿级', 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': True, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '不成', 'zhi_jing': '不净'},
    'LIU7': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第二档·中富中贵', 'gong_points': 2.5, 'gong_shen_cats': ['官杀', '比劫', '食伤'], 'level': 2, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '处级-厅级', 'raw_level': 2, 'reasons': ['原神用神同制：year_zhi(申)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '月令做功：月令戌直接参与核心做功，提纲得时得令（+0.5层）', '制不净：制用动作含空亡/长生折扣，制之未尽，封顶于三层（达不到四层）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 49, 'strength': '中和', 'tier_name': '中富中贵', 'wealth_grade': '千万-亿级', 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'LIU8': {'boundary': 'L2/L3边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用']}, 'gong_points': 4.0, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 4, 'reasons': ['原神用神同制：day_zhi(申)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '七杀当财：官杀透干(year_gan)与制局目标(day_zhi/申)同根，七杀当财（+1层）', '包局2.6：年时天干包局/十神包局（官杀），包围月日且制化所包（+1层）', '制不净：用神「财」之原神「食伤」透干(month_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=68 落 L2/L3边界（不强制二选一，宜结合制净/做功细辨）', '双轨对账：双轨冲突：做功层次L1（效率视角）与功量L3（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 68, 'strength': '从弱', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': True, 'diff': 2, 'gongliang_level': 3, 'note': '双轨冲突：做功层次L1（效率视角）与功量L3（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', 'work_level': 1}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'LIU9': {'boundary': 'L2/L3边界', 'chain_length': 0, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '合用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['原神用神同制：day_zhi(巳)含用神「官杀」与原神「财」同制（+2层，厅级以上贵命）', '七杀当财：官杀透干(month_gan)与制局目标(day_zhi/巳)同根，七杀当财（+1层）', '月令做功：月令申直接参与核心做功，提纲得时得令（+0.5层）', '制不净：日柱被穿，做功质量受损，封顶于三层（达不到四层）', '复合结构：制用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=68 落 L2/L3边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 68, 'strength': '身强', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'yuanshen_yongshen': '官杀+财', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'AONAXIXI': {'boundary': 'L3/L4边界', 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第四档·极富极贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'gong_points': 6.5, 'gong_shen_cats': ['印', '官杀', '比劫', '食伤'], 'level': 4, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '总理-元首级', 'raw_level': 4, 'reasons': ['原神用神同制：month_zhi(丑)含用神「财」与原神「食伤」同制（+2层，千万-亿级富命）', '制墓库：制局冲/刑制墓库「未」（+2层）', '包局/包制：方局（三会）成势围制（+1层）', '月令做功：月令丑直接参与核心做功，提纲得时得令（+0.5层）', '开库加层：做功墓库「未」逢刑冲开库，功上加功（+1层）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制（方局围制+制库双结构，书判四层功量（理象学6470-6474），不净封顶不适用）', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '边界区：score=94 落 L3/L4边界（不强制二选一，宜结合制净/做功细辨）', '贼神捕神上游信号（净制=不净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 94, 'strength': '从强', 'tier_name': '极富极贵', 'wealth_grade': '百亿-千亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 4, 'work_level': 3}, 'yuanshen_yongshen': '财+食伤', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'YANXISHAN': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': True, 'controls': ['印', '官杀', '比劫', '财'], 'fugui_pinjian': '第三档·大富大贵', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '墓用']}, 'gong_points': 3.5, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 3, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '厅级-省部级', 'raw_level': 3, 'reasons': ['入墓为功：局中墓用做功1处（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '化用成局/从杀格：杀印相生化用、官杀「金」党势成(6字)、日主从弱(比劫1字)，纯化用路径（+2层，化用成局为高层功量）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制，封顶于三层（达不到四层）', '复合结构：制用/生用/墓用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）'], 'score': 76, 'strength': '从弱', 'tier_name': '大富大贵', 'wealth_grade': '亿-数十亿级', 'work_level_duizhang': {'conflict': False, 'diff': 1, 'gongliang_level': 3, 'work_level': 2}, 'yuanshen_yongshen': None, 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '无制', 'zhi_jing': '不净'},
    'PUTONG2': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财'], 'fugui_pinjian': '第一档·小富小贵（普通偏上）', 'fuhe': {'conflicts': [], 'detected': True, 'synergy': True, 'types': ['制用', '生用', '合用']}, 'gong_points': 2.5, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 1, 'penalty': '相生之功', 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '科级-处级', 'raw_level': 2, 'reasons': ['带象：month柱己酉干生支，承「财」象且参与做功（+1层）', '月令做功：月令酉直接参与核心做功，提纲得时得令（+0.5层）', '墓库属性：墓库「丑」参与做功，库之属性加层（+1层）', '制不净：用神「财」之原神「食伤」透干(hour_gan)未被净制，封顶于三层（达不到四层）', '普通四柱特征：仅以相生做功，无制局，功量较小', '复合结构：制用/生用/合用并存，方向一致协同（成格标注）——高级篇2.6（标注级，不加点）', '双轨对账：双轨冲突：做功层次L3（效率视角）与功量L1（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', '贼神捕神上游信号（净制=不净；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 0, 'strength': '身弱', 'tier_name': '小富小贵', 'wealth_grade': '百万级', 'work_level_duizhang': {'conflict': True, 'diff': -2, 'gongliang_level': 1, 'note': '双轨冲突：做功层次L3（效率视角）与功量L1（富贵量级）差2层，宜复核（降档/封顶/体系口径差异）', 'work_level': 3}, 'yuanshen_yongshen': None, 'zeishen_bao_zhi': False, 'zeishen_chong_lian': False, 'zeishen_jing_zhi': '不净', 'zhi_jing': '不净'},
    'PUTONG4': {'boundary': None, 'chain_length': 1, 'confidence': '中', 'cong_ge': False, 'controls': ['印', '官杀', '比劫', '财', '食伤'], 'fugui_pinjian': '第二档·中富中贵', 'gong_points': 2.5, 'gong_shen_cats': ['印', '官杀', '比劫', '财', '食伤'], 'level': 2, 'penalty': None, 'pocai_reason': '', 'pocai_severity': None, 'pocai_signal': False, 'rank_grade': '处级-厅级', 'raw_level': 2, 'reasons': ['原神用神同制：day_zhi(午)含用神「印」与原神「官杀」同制（+2层，两层功量）', '月令做功：月令辰直接参与核心做功，提纲得时得令（+0.5层）', '制不净：用神「财」之原神「食伤」透干(year_gan)未被净制，封顶于三层（达不到四层）', '贼神捕神上游信号（净制=净、冲链检出；包制/冲链不重复计入功量点，以本模块保守判为准）'], 'score': 50, 'strength': '身弱', 'tier_name': '中富中贵', 'wealth_grade': '千万-亿级', 'yuanshen_yongshen': '印+官杀', 'zeishen_bao_zhi': False, 'zeishen_chong_lian': True, 'zeishen_jing_zhi': '净', 'zhi_jing': '不净'},
}

def _canon(o):
    """set 排序后序列化（与捕获口径一致）。"""
    if isinstance(o, dict):
        return {k: _canon(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_canon(v) for v in o]
    if isinstance(o, (set, frozenset)):
        return sorted(_canon(v) for v in o)
    return o

def _pipeline(gans, zhis):
    """按 analyze_gongliang 编排序依次跑五阶段（与编排器同参同序）。"""
    day_gan = gans[2]
    inp = _prepare_inputs(None, day_gan, list(gans), list(zhis),
                          work_actions=None, work_types=None,
                          fei_shen=None, gong_shen=None,
                          zeishen_bushen_result=None)
    pos = _compute_position_sets(inp['day_wx'], gans, zhis,
                                 inp['wa_list'], inp['fei'],
                                 inp['gshen'], inp['tomb_works'])
    rules = _apply_gong_point_rules(
        inp['day_gan'], inp['day_wx'], gans, zhis,
        gshen=inp['gshen'], san_he_formed=inp['san_he_formed'],
        non_aux=pos['non_aux'], active_tomb_works=pos['active_tomb_works'],
        involved_positions=pos['involved_positions'],
        zhi_targets=pos['zhi_targets'], gan_cats=pos['gan_cats'],
        strong_positions=pos['strong_positions'],
        destructive_positions=pos['destructive_positions'],
        _zb_bao=inp['zb_bao'], _zb_clian=inp['zb_clian'],
        _zb_jing=inp['zb_jing'])
    caps = _apply_caps_and_direction(
        inp['day_gan'], inp['day_wx'], gans, zhis,
        inp['wa_list'], inp['wtypes'], inp['gshen'], inp['fei'],
        pos['control_action_count'],
        points=rules['points'], involved_cats=pos['involved_cats'],
        zhi_targets=pos['zhi_targets'], gan_cats=pos['gan_cats'],
        fei_cats=pos['fei_cats'], non_aux=pos['non_aux'],
        has_severe_harm=inp['has_severe_harm'],
        _fang_ju_formed=rules['_fang_ju_formed'],
        _zhiku_tombs=rules['_zhiku_tombs'], _zb_jing=inp['zb_jing'],
        _zb_bao_counted=rules['_zb_bao_counted'],
        _zb_pyramid=rules['_zb_pyramid'],
        yuanshen_hit=rules['yuanshen_hit'],
        hua_chengju=rules['hua_chengju'], reasons=rules['reasons'])
    built = _build_gongliang_result(
        day_wx=inp['day_wx'], zg=inp['zg'], gshen=inp['gshen'],
        fei=inp['fei'], non_aux=pos['non_aux'],
        points=rules['points'], reasons=caps['reasons'],
        level=caps['level'], raw_level=caps['raw_level'],
        zhi_jing=caps['zhi_jing'], penalty=caps['penalty'],
        involved_cats=pos['involved_cats'], gong_cats=pos['gong_cats'],
        chain_len=rules['chain_len'],
        yuanshen_hit=rules['yuanshen_hit'],
        _zb_bao_counted=rules['_zb_bao_counted'],
        _zb_boost=rules['_zb_boost'],
        zb_jing_adopted=caps['zb_jing_adopted'],
        yongshen_xiong=caps['yongshen_xiong'], fuhe=caps['fuhe'],
        _strength_gl=caps['_strength_gl'],
        _zb_bao=inp['zb_bao'], _zb_clian=inp['zb_clian'],
        _zb_jing=inp['zb_jing'],
        pocai_signal=caps['pocai_signal'],
        pocai_severity=caps['pocai_severity'],
        pocai_reason=caps['pocai_reason'])
    return inp, pos, rules, caps, built

_FULL = list(PIN)


class TestPrepareInputs:
    """① 输入准备：Pillars/自调/上游信号解析。"""

    @pytest.mark.parametrize('pan', _FULL)
    def test_prepare_projection(self, pan):
        gans, zhis = PANS[pan]
        inp, *_ = _pipeline(gans, zhis)
        pin = PIN[pan]['ph1']
        proj = {k: _canon(inp[k]) for k in ('wtypes', 'fei', 'gshen',
                'tomb_works', 'san_he_formed', 'has_severe_harm', 'zb',
                'zb_bao', 'zb_clian', 'zb_jing', 'day_gan', 'day_wx')}
        assert proj == {k: pin[k] for k in proj}
        assert len(inp['wa_list']) == pin['_wa_list_len']

class TestComputePositionSets:
    """② 位置与十神集合。"""

    @pytest.mark.parametrize('pan', _FULL)
    def test_position_sets(self, pan):
        gans, zhis = PANS[pan]
        _, pos, *_ = _pipeline(gans, zhis)
        assert _canon(pos) == PIN[pan]['ph2']

class TestApplyGongPointRules:
    """③ 14 条计分规则集中。"""

    @pytest.mark.parametrize('pan', _FULL)
    def test_gong_point_rules(self, pan):
        gans, zhis = PANS[pan]
        _, _, rules, _, _ = _pipeline(gans, zhis)
        assert _canon(rules) == PIN[pan]['ph3']

class TestApplyCapsAndDirection:
    """④ 封顶/降档/方向标注。"""

    @pytest.mark.parametrize('pan', _FULL)
    def test_caps_and_direction(self, pan):
        gans, zhis = PANS[pan]
        _, _, _, caps, _ = _pipeline(gans, zhis)
        assert _canon(caps) == PIN[pan]['ph4']

class TestBuildGongliangResult:
    """⑤ 装配输出/双轨对账/zb 信号录入。"""

    @pytest.mark.parametrize('pan', _FULL)
    def test_build_result(self, pan):
        gans, zhis = PANS[pan]
        *_, built = _pipeline(gans, zhis)
        assert _canon(built) == PIN[pan]['ph5_result']

class TestEndToEnd:
    """端到端：analyze_gongliang 全量输出 == 拆分前实测。"""

    @pytest.mark.parametrize('pan', list(PANS))
    def test_analyze_gongliang_unchanged(self, pan):
        gans, zhis = PANS[pan]
        r = analyze_gongliang(day_gan=gans[2], gans=list(gans), zhis=list(zhis))
        assert _canon(r) == BOOK_A[pan]

    @pytest.mark.parametrize('pan', list(PILLARS_PIN))
    def test_analyze_gongliang_pillars_signature(self, pan):
        gans, zhis = PANS[pan]
        p = Pillars(gans[0], zhis[0], gans[1], zhis[1],
                    gans[2], zhis[2], gans[3], zhis[3])
        r = analyze_gongliang(p)
        assert _canon(r) == PILLARS_PIN[pan]

